### ISSUE TITLE
Verify HORNET(v0.4.0-rc8) integration with dcurl

### ISSUE THREAD

**Issue by JulianATA** [DLTcollab/general#251] opened 2020-04-27 05:22 UTC
## Integration
The integration includes 2 commits:
* feat: [Integrate HORNET with dcurl CGO interface](https://github.com/JulianATA/hornet/commit/21e26cda89889e5c831357c6977a73c28cd45cb7)
    * Replacing PoW functions in plugins/spammer/spammer.go and plugins/webapi/pow.go
* docs: Include dcurl CGO api in GO module
    * Update go.mod and go.sum for maintaining 

## Preparation for dcurl
* libdcurl.so from dcurl
* Set the library paths

From commonly use:
```
$ git clone https://github.com/DLTcollab/dcurl.git
$ cd dcurl
$ make
$ export LIBRARY_PATH=$(pwd)/build
$ export LD_LIBRARY_PATH=$(pwd)/build
```

From debugging or testing(debug mode):
```
$ git clone https://github.com/DLTcollab/dcurl.git
$ cd dcurl
$ make BUILD_DEBUG=1
$ export LIBRARY_PATH=$(pwd)/build
$ export LD_LIBRARY_PATH=$(pwd)/build
```

## Run HORNET v0.4.0-rc8-dcurl
* clone from temporarily repository
* branch: v0.4.0-rc8-dcurl
```
$ git clone https://github.com/JulianATA/hornet -b v0.4.0-rc8-dcurl
$ cd hornet
```
* check go packages using go build
```
$ go build
```
* Run
```
$ ./hornet
```

## Verification
* With dcurl in debug mode, we should see logs like below when doing proof of work

On node 1:
```
[dcurl] Implementation CPU (Intel AVX) is initialized successfully
```

**Comment by marktwtn** [comment] 2020-05-05 07:55
I use **pyota** to send `attachToTangle` API to the Hornet on `DE10-Nano` board.

However, it returns with the error:
```
HTTPError: HTTP Error 500: Internal Server Error
```

and the Hornet shows the error message:
```
2020/05/05 07:42:30 [Recovery] 2020/05/05 - 07:42:30 panic recovered:
runtime error: slice bounds out of range [:-1]
/usr/local/go/src/runtime/panic.go:98 (0x4f4a3)
        goPanicSliceAlen: panic(boundsError{x: int64(x), signed: true, y: y, code: boundsSliceAlen})
/home/ubuntu/go/pkg/mod/github.com/dltcollab/dcurl/cgo@v0.0.0-20200415093323-
2930b63834c8/pow/pow.go:75 (0x8abc1b)
        DcurlEntry: nonce := returnTrytesGO[len(returnTrytesGO)-NonceTrinarySize/3-1 : len(returnTrytesGO)-1]
/home/ubuntu/go/pkg/mod/github.com/dltcollab/dcurl/cgo@v0.0.0-20200415093323-
2930b63834c8/pow/pow.go:54 (0x8aba1b)
        SyncDcurlProofOfWork: nonce, err := DcurlEntry(trytes, mwm, parallelism...)
/home/ubuntu/julian/hornet/plugins/webapi/pow.go:114 (0x8bab13)
        attachToTangle: txs[i].Nonce, err = powFunc(trytes, query.MinWeightMagnitude)
/home/ubuntu/julian/hornet/plugins/webapi/api.go:69 (0x8bdacf)
        webAPIRoute.func1: implementation(&request, c, serverShutdownSignal)
/home/ubuntu/go/pkg/mod/github.com/gin-gonic/gin@v1.6.1/context.go:152 (0x79557ff)
        (*Context).Next: c.handlers[c.index](c)
/home/ubuntu/julian/hornet/plugins/webapi/plugin.go:65 (0x8be923)
        configure.func1: c.Next()
/home/ubuntu/go/pkg/mod/github.com/gin-gonic/gin@v1.6.1/context.go:152 (0x79557ff)
        (*Context).Next: c.handlers[c.index](c)
/home/ubuntu/go/pkg/mod/github.com/gin-gonic/gin@v1.6.1/recovery.go:83 (0x7a60333)
        RecoveryWithWriter.func1: c.Next()
/home/ubuntu/go/pkg/mod/github.com/gin-gonic/gin@v1.6.1/context.go:152 (0x79557ff)
        (*Context).Next: c.handlers[c.index](c)
/home/ubuntu/go/pkg/mod/github.com/gin-gonic/gin@v1.6.1/gin.go:409 (0x79dba7)
        (*Engine).handleHTTPRequest: c.Next()
/home/ubuntu/go/pkg/mod/github.com/gin-gonic/gin@v1.6.1/gin.go:367 (0x79d463)
        (*Engine).ServeHTTP: engine.handleHTTPRequest(c)
/usr/local/go/src/net/http/server.go:2807 (0x351433)
        serverHandler.ServeHTTP: handler.ServeHTTP(rw, req)
/usr/local/go/src/net/http/server.go:1895 (0x34d923)
        (*conn).serve: serverHandler{c.server}.ServeHTTP(w, w.req)
/usr/local/go/src/runtime/asm_arm.s:857 (0x845cf)
        goexit: MOVW    R0, R0  // NOP
```

**Comment by marktwtn** [comment] 2020-05-10 11:13
The source code **cgo/pow/pow.go** of **dcurl**
```
func DcurlEntry(trytes Trytes, mwm int, parallelism ...int) (Trytes, error) {
	if trytes == "" {
		return "", errors.New("invalid trytes supplied to Proof-of-Work func")
	}

	var numThread int
	if len(parallelism) != 0 && parallelism[0] > 0 {
		numThread = parallelism[0]
	} else {
		numThread = 1
	}

	returnTrytesC := C.dcurl_wrapper(C.CString(trytes), C.int(mwm), C.int(numThread))
	returnTrytesGO := C.GoString(returnTrytesC)
	nonce := returnTrytesGO[len(returnTrytesGO)-NonceTrinarySize/3-1 : len(returnTrytesGO)-1]

	return nonce, nil
}
```

It turns out that on the `DE10-Nano` with the integration of `Hornet`,
the input `trytes` has the value but the `returnTrytesGO` is an empty string.

**Comment by marktwtn** [comment] 2020-05-11 02:44
The problem on `DE10-Nano` is caused by the unsuccessful initialization of `dcurl`.
The return value of available physical CPUs and threads per core is `-1`, which causes the initialization failed.

However, it only happens when the `Hornet` is integrated with `dcurl`.
When running the `dcurl` `cgo` test, it has no problem at all.

**Comment by marktwtn** [comment] 2020-05-11 13:27
The problem happens in the function `get_nthds_per_phys_proc()` of `dcurl`.
```
fd = popen("LC_ALL=C lscpu | grep 'Thread(s) per core' | awk '{printf $4}'", "r"); 
```

Based on the description of [popen](http://man7.org/linux/man-pages/man3/popen.3.html),

popen(): on success, returns a pointer to an open stream that can be used to read or write to the pipe; **if the fork(2) or pipe(2) calls fail, or if the function cannot allocate memory, NULL is returned.**

**Comment by marktwtn** [comment] 2020-05-11 16:01
I use the `strerror(errno)` to check the detailed error message.
The result is **Cannot allocate memory**, and the memory of `DE10-Nano` is 1GB.

c.c. @yillkid

**Comment by marktwtn** [comment] 2020-05-15 01:27
Here is the conclusion of the integration of `Hornet` and `dcurl` on `DE10-Nano`.

- Use CPU acceleration
    The current initialization of getting the CPU hyperthreading status uses the function:
    ```
    popen("LC_ALL=C lscpu | grep 'Thread(s) per core' | awk '{printf $4}'", "r");
    ```
    The `popen()` would call the `fork()`.
However, the parent process `Hornet` uses almost 80% of the memory on `DE10-Nano`, hence `fork()` would fail with the error **Cannot allocate memory**.
In order to let the CPU acceleration succeed, we have to avoid using `fork()`.
The new implementation would be parsing the file `/proc/cpuinfo` directly.
There are 2 possible parsing rules:
    - [lscpu source code implementation](https://github.com/karelzak/util-linux/blob/master/sys-utils/lscpu.c)
    - Check whether the `ht` flags exists or not first, then check the value of `siblings` and `cpu cores`.

    The new hyperthreading detection issue does not have to be put in a high priority.
The reason is the `fork()` failure only happpens when the hardware memory is limited and I believe we would not use the kind of the limited hardware for PoW CPU acceleration.
But I will open a corresponding issue on the `dcurl` repository.

- Use FPGA acceleration
The integration runs well.
But the root privilege should be handled well as mention in https://github.com/DLTcollab/dcurl/issues/217#issuecomment-612585688.

@jserv is the conclusion acceptable?
@yillkid the **attachToTangle** API of `Hornet` has already tested.

**Comment by jserv** [comment] 2020-05-15 02:56
For DE10-Nano, we shall concentrate on FPGA accelerations rather than CPU-based multiprocessing.

**Comment by marktwtn** [comment] 2020-05-15 03:00
@JulianATA after you finish the pull request https://github.com/DLTcollab/dcurl/pull/229 and I figure out the privilege problem, we can close the issue.

**Comment by marktwtn** [comment] 2020-05-19 10:21
In order to run the `Hornet` with FPGA enabled on `DE10-Nano`, please use the instruction:
```
$ sudo env LD_LIBRARY_PATH=[path_of_libdcurl.so] ./hornet
```

The reasons are:

1. Using FPGA acceleration requires root privilege.
2. Using `sudo` would make the required environment variables back to their original value, hence the `env` command is necessary to assign the value to environment variables. We need to make sure that when `Hornet` is executing PoW with `dcurl`, it can find the `dcurl` shared library.

**Closed by marktwtn** 2020-05-19 10:21 UTC
Labels: help wanted
